#!/bin/bash

# Ensure the destination directories exist
mkdir -p public/dist
mkdir -p public/mqeditor/build
mkdir -p public/style

# Move folders and file to the corresponding destinations
cp -r dist public/
cp -r mqeditor/build public/mqeditor/
cp -r style public/
cp -r index.html public/